### ISSUE TITLE
Add integration test for each command

### ISSUE THREAD

**Issue by ryota-sakamoto** [awslabs/dynein#143]
## Background

We need to check compatibility through test before pull request is merged. For now, some integration tests are implemented but we haven't covered all of the command. So we need to add integration test for all of the command.

## Tasks
- [x] admin:
  - [x] admin create: #234
  - [x] admin delete: #194 
  - [x] admin desc: #161
  - [x] admin list: #166 
  - [x] admin update: #229
- [x] backup: #235
- [x] bootstrap: #153
- [x] bwrite: #190
- [x] config: #148 
- [x] del: #144 
- [x] desc: #151 
- [x] export: #181 
- [x] get: #142 
- [x] import: #230
- [x] list: #158
  - [x] show current table: #180 
- [x] put: #232
- [x] query: #218
- [x] restore:  #233
- [x] scan: #217
- [x] upd: #226
- [x] use: #227

**Comment by StoneDot** [comment]
@kzym-w, Could you assess the quality of the test for the query command? I have added tests in #187, so new tests may no longer be needed.

**Comment by StoneDot** [comment]
I have contacted kzym-w and I will take over the tests for the query.

**Comment by StoneDot** [comment]
We have added integration tests for all commands. I will close this.
