### ISSUE TITLE
list tables does not work for local region

### ISSUE THREAD

**Issue by tadvi** [awslabs/dynein#18]
List tables does not work for local region

$ dy -r local list
or
$ dy admin -r local list

fails with 
```
[2021-03-01T02:25:07Z ERROR dy::app] 
    To execute the command you must specify target table in one of following ways:
        * [RECOMMENDED] $ dy use <your_table> ... save target table to use.
        * Or, optionally you can pass --region and --table options to specify target for your commands. Refer --help for more information.
    To find all tables in all regions, try:
        * $ dy ls --all-regions
```

I have used
$ dy -r local bootstrap
and it worked fine populating database with 4 tables. 
Other individual commands to scan and query tables work on those tables and -r local.

**Comment by thash** [comment]
Hi, thank you for reporting it. Let me share the current status of the issue.

After investigation, I have identified the issue can happen when `~/.dynein/cache.yml` contains at least one cached table, but `~/.dynein/config.yml` doesn't have any "using" table. Here's my reproduction steps to replicate your issue.

```
$ dy --version
dynein 0.1.2
$ dy config clear
$ dy config dump
---
tables: ~
---
using_region: ~
using_table: ~

$ dy -r local list ### works fine
DynamoDB tables in region: local
  Forum
  ProductCatalog
  Reply
  Thread

$ dy -r local desc Forum 1>/dev/null ### to cache a table in ~/.dynein/cache.yml
$ dy config dump
---
tables:
  local/Forum:
    region: local
    name: Forum
    pk:
      name: Name
      kind: S
    sk: ~
    indexes: ~
    mode: OnDemand
---
using_region: ~
using_table: ~

$ dy -r local list ### error
DynamoDB tables in region: local
[2021-07-21T18:52:47Z ERROR dy::app]
    To execute the command you must specify target table in one of following ways:
        * [RECOMMENDED] $ dy use <your_table> ... save target table to use.
        * Or, optionally you can pass --region and --table options to specify target for your commands. Refer --help for more information.
    To find all tables in all regions, try:
        * $ dy ls --all-regions
```

We'll need to modify the code to radically prevent this issue, I apologize for the inconvenience. For now, as a workaround, you can do `$ dy use <your_table_name>` or simply clear cached tables info by using `$ dy config clear` when you encounter the issue.

Please let me know if you need further assistance concerning the issue.
