### ISSUE TITLE
Release pre-built binaries for macOS ARM

### ISSUE THREAD

**Issue by suzuki-shunsuke** [awslabs/dynein#222]
https://github.com/awslabs/dynein/blob/22ba13306d7fc0a4c321230a9490d44e7ec4b542/README.md?plain=1#L80

> Currently, the above binary is automatically built on intel mac as [the GitHub Action doesn't support Apple M1 (ARM) environment yet](https://github.com/actions/virtual-environments/issues/2187). 

Now GitHub Actions supports Apple M1 ARM.

- https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/
- https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

So we can release pre-built binaries for macOS ARM by GitHub Actions.

**Comment by suzuki-shunsuke** [comment]
I've created a pull request.

- #223

**Comment by StoneDot** [comment]
We released [v0.3.0](https://github.com/awslabs/dynein/releases/tag/v0.3.0), which contains the binary for macOS ARM.
