### ISSUE TITLE
Update `ThirdPartyAttribution.br` for version 0.3.0 release

### ISSUE THREAD

**Issue by StoneDot** [awslabs/dynein#239]
We need to update [ThirdPartyAttribution.br](https://github.com/awslabs/dynein/blob/main/src/resources/attribution/ThirdPartyAttribution.br) file just before releasing it.

**Comment by KIrie-0217** [comment]
I'll update attribution file when #126 is merged.

**Comment by StoneDot** [comment]
We have completed the update of `ThirdPartyAttribution.br` by #246.
