### ISSUE TITLE
Binary release are linked with libssl.so.1.1 which is not present in some distribution

### ISSUE THREAD

**Issue by gaetan-craft** [awslabs/dynein#248]
I tried to install dy in an ec2 instance running AL2023 which have openssl 3.0.8 and no package for libssl 1.1 which lead to an unusable binary.

Should it possible to have a static binary for the project usable everywhere ?

**Comment by StoneDot** [comment]
Based on my investigation, removing the dependency to `reqwest` make it possible. I will create a new pull request to address this issue. I expect the release of the new binary, which fixes the problem, will come after release `v0.3.0` because we have already frozen the `v0.3.0` dependency.

**Comment by gaetan-craft** [comment]
Thanks a lot for your reactivity!
If I read correctly the github action yaml 3.0 build we'll be done on ubuntu-latest which use libssl3 widely available

**Comment by StoneDot** [comment]
>  If I read correctly the github action yaml 3.0 build we'll be done on ubuntu-latest which use libssl3 widely available

It should be accurate, but I can only say the exact thing once we actually create a new binary. I hope `v0.3.0` is available on your environment. I wrote down the current situation for you to look over.

---

We use `ubuntu-latest`.
https://github.com/awslabs/dynein/blob/9f8f6fd6d83e49ad4a88ba57cf01b6421e225e8a/.github/workflows/build_binaries_on_new_releases.yml#L20

`ubuntu-latest` is currently the same as `ubuntu-22.04`.
https://github.com/actions/runner-images

Ubuntu 22.04 uses OpenSSL 3.0.2.
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
> OpenSSL 3.0.2-0ubuntu1.15

**Comment by gaetan-craft** [comment]
I did the build of 2.10 on a Ubuntu 22.04 and the binary worked on al2023 so I'm pretty confident it would work.
Do you have an idea of when the 3.0 will be released?

Thanks again
