### ISSUE TITLE
Migrate from rusoto to AWS SDK for Rust

### ISSUE THREAD

**Issue by ghost** [awslabs/dynein#51]
AWS SDK for Rust is now in developer preview.
https://aws.amazon.com/jp/about-aws/whats-new/2021/12/aws-sdk-rust-developer-preview/

For future GA, we start to consider migrating rusoto to AWS SDK for Rust.

**Comment by itazur** [comment]
Handling DynamoDB Local is different between AWS SDK for Rust and rusoto.

rusoto specifies the endpoint when creating a region as `Region::Custom`.
On the other hand, AWS SDK for Rust specifies the endpoint when building `Config`.

An example of how to use DynamoDB Local is provided in the following link.
https://docs.aws.amazon.com/sdk-for-rust/latest/dg/dynamodb-local.html
