### ISSUE TITLE
How about rename cmd `dy` to `ddb`?

### ISSUE THREAD

**Issue by wchaws** [awslabs/dynein#79]
`dy` is pronounced similarly to `die`, which is a bad name in my view. I would prefer `ddb` because it's a very common service acronym for DynamoDB.

**Comment by anhtumai** [comment]
you can set an `alias` in your `.bashrc` or `.zshrc` if you use Linux or Mac

**Comment by anhtumai** [comment]
type: `which dy` to see the full path to `dy` binary
`alias ddb=<full-path-to-dy-binary>`

**Comment by StoneDot** [comment]
Thank you for opening the issue, and I'm sorry for the delay in response.

Firstly, we don't specify a pronunciation of `dy` command. For example, you can call it /díːwάɪ/ or /daɪ.nɪn/. `dy` comes from `dynein`, our project name. `dy` was chosen by the convenience of typing as commonly seen on Rust projects. Thus, we have no plan to change this command name.

As anhtumai is suggested, you can use an alias.

I believe the above comment is sufficient for your concerns; thus, please let me close this issue. If you have any problems or questions, please feel free to reopen this issue and add comments.
