### ISSUE TITLE
Cannot update a string attribute with an UUID.

### ISSUE THREAD

**Issue by Ludonope** [awslabs/dynein#92]
Trying to set a string attribute to a UUID fails, it seems like it tries to parse it as if it was an operation on number, however the quotes should indicate that it is a raw string.

```
> dy upd item1Key --set 'Attribute = "00000000-0000-0000-0000-000000000000"' --table DataTable
2022-05-17T21:47:25Z ERROR dy::data] failed to parse a right hand statement '"00000000-0000-0000-0000-000000000000"'. Valid syntax would be: 'Attr = "val"', or 'Attr = Attr + 100'
```

Weirdly enough passing `"a00000000-0000-0000-0000-000000000000"` or `"-00000000-0000-0000-0000-000000000000"` fails too, not sure where it comes from but it definitely looks like a bug. If not the solution should be made clear in the documentation.

**Comment by StoneDot** [comment]
This issue has been resolved by #132. We have plans to release it in v0.3.0.
